---

- name: Install KDE packages
  ansible.builtin.dnf:
    state: present
    name:
      - latte-dock
      - kwalletcli
      - kmail
      - korganizer
      - plasma-discover-packagekit
      - PackageKit-Qt5
