---

- name: Install KDE packages
  community.general.pacman:
    state: present
    name:
      - latte-dock
      - kmail
      - korganizer
      - packagekit-qt5

- name: Check if mksh is installed
  ansible.builtin.stat:
    path: /usr/bin/mksh
  register: stat_mksh

- name: Clone mksh from aur
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/mksh.git
    dest: /tmp/mksh
    version: master
    update: yes
  when: not stat_mksh.stat.exists

- name: Install mksh using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/mksh
    creates: /usr/bin/mksh
  when: not stat_mksh.stat.exists

- name: Check if mksh installation was succesful
  ansible.builtin.stat:
    path: /usr/bin/mksh
  register: stat_mkshinstalled

- name: Remove mksh cloned repository
  ansible.builtin.file:
    path: /tmp/mksh
    state: absent
  when: stat_mkshinstalled.stat.exists

- name: Check if kwalletcli is installed
  ansible.builtin.stat:
    path: /usr/bin/kwalletcli
  register: stat_kwalletcli

- name: Clone kwalletcli from aur
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/kwalletcli.git
    dest: /tmp/kwalletcli
    version: master
    update: yes
  when: not stat_kwalletcli.stat.exists

- name: Install kwalletcli using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/kwalletcli
    creates: /usr/bin/kwalletcli
  when: not stat_kwalletcli.stat.exists

- name: Check if kwalletcli installation was succesful
  ansible.builtin.stat:
    path: /usr/bin/kwalletcli
  register: stat_kwalletcliinstalled

- name: Remove kwalletcli cloned repository
  ansible.builtin.file:
    path: /tmp/kwalletcli
    state: absent
  when: stat_kwalletcliinstalled.stat.exists

- name: Create sddm config dir
  ansible.builtin.file:
    path: /etc/sddm.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure sddm to use the breeze theme
  ansible.builtin.copy:
    dest: /etc/sddm.conf.d/breeze.conf
    owner: root
    group: root
    mode: '0644'
    content: |
        [Theme]
        Current=breeze
        CursorTheme=breeze_cursors
