---

- name: Ensure all required directories exist
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'
    state: directory
  loop:
    - .gnupg
    - .config/autostart-scripts
    - .config/plasma-workspace
    - .config/plasma-workspace/shutdown
    - .config/plasma-workspace/env

- name: Configure kde pinentry for gpg + kwallet
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.gnupg/gpg-agent.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0640'
    content: |
        pinentry-program /usr/bin/pinentry-kwallet

- name: Add ssh key passphrase to kwallet during autostart
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/autostart-scripts/ssh-add.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'
    content: |
        #!/usr/bin/env bash
        sleep 10
        SSH_ASKPASS=/usr/bin/ksshaskpass
        export SSH_ASKPASS
        ssh-add ~/.ssh/id_ed25519

- name: Configure ssh agent to stop on shutdown
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/plasma-workspace/shutdown/ssh-agent-shutdown.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'
    content: |
        #!/usr/bin/env bash
        [ -z "$SSH_AGENT_PID" ] || eval "$(ssh-agent -k)"

- name: Configure ssh agent to start on login
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/plasma-workspace/env/ssh-agent-startup.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'
    content: |
        #!/usr/bin/env bash
        [ -n "$SSH_AGENT_PID" ] || eval "$(ssh-agent -s)"
        SSH_ASKPASS=/usr/bin/ksshaskpass
        export SSH_ASKPASS

- name: Configure snap XDG_DATA_DIRS for snaps
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/plasma-workspace/env/snaps.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0750'
    content: |
        #!/usr/bin/env bash
        export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/snapd/desktop/"

- name: Configure ssh askpass in profile.d
  ansible.builtin.copy:
    dest: /etc/profile.d/ksshaskpass.sh
    owner: root
    group: root
    mode: '0750'
    content: |
        #!/usr/bin/env bash
        SSH_ASKPASS=/usr/bin/ksshaskpass
  become_user: root
  become: yes

- name: Configure monospace font
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kdeglobals --group General --key fixed 'Hack,10,-1,5,50,0,0,0,0,0'"

- name: Configure touchpad
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kcminputrc --group Lininput --group 2 --group 14 --group 'ETPS/2 Elantech Touchpad' --key {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'ClickMethod', value: '1' }
    - { key: 'ScrollMethod', value: '1' }
    - { key: 'NaturalScroll', value: 'true' }
    - { key: 'ScrollFactor', value: '4' }
    - { key: 'TapAndDrag', value: 'true' }
    - { key: 'TapToClick', value: 'true' }

- name: Configure mouse
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kcminputrc --group Mouse --key XLbInptNaturalScroll true"

- name: Configure night colour
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kwinrc --group NightColor --key {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'Active', value: 'true' }
    - { key: 'LatitudeAuto', value: '53.2018' }
    - { key: 'LongitudeAuto', value: '6.5907' }

- name: Configure middle-click minimise for windows
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kwinrc --group MouseBindings --key {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'CommandActiveTitlebar2', value: 'Minimize' }
    - { key: 'CommandAll2', value: 'Resize' }
    - { key: 'CommandInactiveTitlebar2', value: 'Minimize'}

- name: Configure screenshot keyboard shortcuts
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kglobalshortcutsrc --group org.kde.spectacle.desktop --key {{ item.key }} {{ item.value }}"
  loop:
    - { key: 'ActiveWindowScreenShot', value: 'Alt+@,Meta+Print,Meta+Print,Capture Active Window' }
    - { key: 'CurrentMonitorScreenShot', value: ',none,Capture Current Monitor' }
    - { key: 'FullScreenScreenShot', value: 'Alt+#,Shift+Print,Shift+Print,Capture Entire Desktop' }
    - { key: 'RectangularRegionScreenShot', value: 'Meta+Shift+Print,Alt+$,Meta+Shift+Print,Capture Rectangular Region' }

- name: Disable mouse over screen edges activies
  ansible.builtin.shell:
    cmd: "kwriteconfig5 --file kwinrc --group {{ item.group }} --key {{ item.key }} {{ item.value }}"
  loop:
    - { group: 'Effect-PresentWindows', key: 'BorderActivateAll', value: '9' }
    - { group: 'TabBox', key: 'BorderActivate', value: '9' }
