---

- name: Getting process IDs of the kde process
  community.general.pids:
    name: /usr/bin/kded5
  register: pids_of_kde

- name: Getting process IDs of the gnome process
  community.general.pids:
    name: /usr/bin/gnome-shell
  register: pids_of_gnome

- name: Set desktop_environment fact to KDE
  ansible.builtin.set_fact: desktop_environment="kde"
  when: pids_of_kde.pids.0 is defined

- name: Set desktop_environment fact to GNOME
  ansible.builtin.set_fact: desktop_environment="gnome"
  when: pids_of_gnome.pids.0 is defined

- name: Include the KDE role
  ansible.builtin.include_role:
    name: kde
  when: desktop_environment == "kde"

- name: Include the GNOME role
  ansible.builtin.include_role:
    name: gnome
  when: desktop_environment == "gnome"
