---

- name: Install virtualisation for Debian based systems
  ansible.builtin.include_tasks: virtualisation_debian.yml
  when: ansible_os_family == "Debian"

- name: Install virtualisation for Fedora based systems
  ansible.builtin.include_tasks: virtualisation_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install virtualisation for Arch Linux based systems
  ansible.builtin.include_tasks: virtualisation_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Include common virtualisation options
  ansible.builtin.include_tasks: virtualisation_common.yml
