---

- name: Install Virtualization group package
  ansible.builtin.dnf:
    name: '@Virtualization'
    state: present

- name: Set libvirtd socket read-write permissions
  replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    replace: 'unix_sock_rw_perms = "0770"'
  notify:
    - Restart and enable libvirtd on fedora

- name: Start and enable libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Append user to libvirt group
  user:
    name: "{{ username }}"
    append: yes
    groups: libvirt
