---

- name: Install virtualisation packages for ubuntu
  ansible.builtin.apt:
    state: present
    pkg:
      - qemu
      - qemu-kvm
      - libvirt-daemon-system
      - virt-manager
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "KDE neon"

- name: Install virtualisation packages for debian
  ansible.builtin.apt:
    state: present
    pkg:
      - qemu
      - libvirt-daemon-system
      - virt-manager
  when: ansible_distribution == "Debian"

- name: Append user to libvirt group
  ansible.builtin.user:
    name: "{{ username }}"
    append: yes
    groups: libvirt
