---

- name: install Virtualization group package
  dnf:
    name: '@Virtualization'
    state: present

- name: set libvirtd socket read-write permissions
  replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    replace: 'unix_sock_rw_perms = "0770"'
  notify:
  - restart and enable libvirtd on fedora

- name: start and enable libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: append user to libvirt group
  user:
    name: "{{ username }}"
    append: yes
    groups: libvirt