---

- name: Ensure the bash completion directory exists
  ansible.builtin.file:
    dest: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure tab completion for virt-viewer
  ansible.builtin.copy:
    dest: /etc/bash_completion.d/virt-viewer
    src: virt-viewer
    owner: root
    group: root
    mode: '0644'
