---

- name: install virtualisation packages
  apt:
    state: present
    pkg:
    - qemu
    - qemu-kvm
    - libvirt-daemon-system
    - virt-manager

- name: append user to libvirt group
  user:
    name: "{{ username }}"
    append: yes
    groups: libvirt