---

- name: Restart auditd service
  systemd:
    name: auditd
    state: restarted
  when: configure_auditd.changed

- name: Remove uncommon network protocol kernel modules
  command: "rmmod {{ item }}"
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - udf
  when: uncommon_filesystem_configs.changed
  ignore_errors: yes

- name: Apply logging of suspicious packets
  command: sysctl -p /etc/sysctl.d/20-cis_log_suspicious_packets.conf

- name: Apply ignore ICMP broadcast
  command: sysctl -p /etc/sysctl.d/20-cis_ignore_icmp_broadcast.conf

- name: Apply ignore bogus ICMP
  command: sysctl -p /etc/sysctl.d/20-cis_ignore_bogus_icmp.conf

- name: Apply ensure reverse path filtering
  command: sysctl -p /etc/sysctl.d/20-cis_ensure_reverse_path_filtering.conf

- name: Apply ensure TCP SYN cookies
  command: sysctl -p /etc/sysctl.d/20-cis_ensure_tcp_syn_cookies.conf

- name: Apply sysctl SUID dumpable
  command: sysctl -p /etc/sysctl.d/20-cis_suid_dumpable.conf

- name: Apply sysctl Address Space Layout Randomisation
  command: sysctl -p /etc/sysctl.d/20-cis_aslr.conf

- name: Manually remount /tmp with noexec permissions
  mount:
    path: /tmp
    opts: noexec
    state: remounted