---

- name: Restart auditd service
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  ignore_errors: True

- name: Remove uncommon filesystem kernel modules
  ansible.builtin.command:
    cmd: "rmmod {{ item }}"
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - udf
  ignore_errors: yes

- name: Remove uncommon network protocol kernel modules
  ansible.builtin.command:
    cmd: "rmmod {{ item }}"
  with_items:
    - dccp
    - sctp
    - rds
    - tipc
  ignore_errors: yes

- name: Apply logging of suspicious packets
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_log_suspicious_packets.conf

- name: Apply ignore ICMP broadcast
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_ignore_icmp_broadcast.conf

- name: Apply ignore bogus ICMP
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_ignore_bogus_icmp.conf

- name: Apply ensure reverse path filtering
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_ensure_reverse_path_filtering.conf

- name: Apply ensure TCP SYN cookies
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_ensure_tcp_syn_cookies.conf

- name: Apply sysctl SUID dumpable
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_suid_dumpable.conf

- name: Apply sysctl Address Space Layout Randomisation
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/20-cis_aslr.conf

- name: Manually remount /tmp with noexec permissions
  ansible.posix.mount:
    path: /tmp
    opts: noexec
    state: remounted
