---

- name: Configure user globals
  ansible.builtin.include_tasks: user_globals.yml

- name: Install user for Debian based systems
  ansible.builtin.include_tasks: user_debian.yml
  when: ansible_os_family == "Debian"

- name: Install user for Fedora based systems
  ansible.builtin.include_tasks: user_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install user for Arch Linux based systems
  ansible.builtin.include_tasks: user_archlinux.yml
  when: ansible_os_family == "Archlinux"
