---

- name: configure user globals
  include_tasks: user_globals.yml

- name: install user for Debian based systems
  include_tasks: user_debian.yml
  when: ansible_os_family == "Debian"

- name: install user for RedHat based systems
  include_tasks: user_fedora.yml
  when: ansible_os_family == "RedHat"

- name: install user for Arch Linux based systems
  include_tasks: user_archlinux.yml
  when: ansible_os_family == "Archlinux"
