---

- name: Create audit group
  group:
    name: audit
    state: present
    system: yes

- name: Append user to groups
  user:
    name: "{{ username }}"
    append: yes
    groups: wheel,libvirt,input,docker,audit,adbusers,informant

- name: Configure passwordless sudo and wheel for pacman commands
  ansible.builtin.copy:
    dest: /etc/sudoers.d/pacman
    owner: root
    group: root
    mode: '0440'
    content: |
      #Allow members of group sudo to execute pacman commands
      Cmnd_Alias PACMAN = /usr/bin/pacman *

      %wheel ALL = NOPASSWD: PACMAN
