---

- name: create "docker" group
  group:
    name: docker
    state: present
    system: yes

- name: append user to groups
  user:
    name: "{{ username }}"
    append: yes
    groups: adm,cdrom,sudo,dip,plugdev,input,lpadmin,sambashare,libvirt,docker

- name: configure passwordless sudo for apt commands
  copy:
    dest: /etc/sudoers.d/apt
    owner: root
    group: root
    mode: '0440'
    content: |
      #Allow members of group sudo to execute apt commands
      Cmnd_Alias APT = /usr/bin/apt update, \
                 /usr/bin/apt full-upgrade, \
                 /usr/bin/apt full-upgrade -y, \
                 /usr/bin/apt install *, \
                 /usr/bin/apt remove *, \
                 /usr/bin/apt purge *, \
                 /usr/bin/apt autoremove, \
                 /usr/bin/apt autoremove -y \

      %sudo ALL = NOPASSWD: APT

- name: configure passwordless sudo for wireguard commands
  copy:
    dest: /etc/sudoers.d/wireguard
    owner: root
    group: root
    mode: '0440'
    content: |
      #Allow members of group sudo to execute wireguard commands
      Cmnd_Alias WIREGUARD = /usr/bin/wg show, \
                             /usr/bin/wg-quick up wg0, \
                             /usr/bin/wg-quick down wg0

      %sudo ALL = NOPASSWD: WIREGUARD

- name: configure bashrc for the user
  get_url:
    url: https://kn0x.org/data/bashrc
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: configure bashrc for root
  get_url:
    url: https://kn0x.org/data/bashrc
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: '0644'

- name: check if user's vim config exists
  stat:
    path: "/home/{{ username }}/.vimrc"
  register: stat_user_vimrc

- name: configure vimrc for the user
  get_url:
    url: https://kn0x.org/data/vimrc
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  when: not stat_user_vimrc.stat.exists

- name: check if root's vim config exists
  stat:
    path: "/home/root/.vimrc"
  register: stat_root_vimrc

- name: configure vimrc for root
  get_url:
    url: https://kn0x.org/data/vimrc
    dest: "/root/.vimrc"
    owner: root
    group: root
    mode: '0644'
  when: not stat_root_vimrc.stat.exists
