---

- name: append user to groups
  user:
    name: "{{ username }}"
    append: yes
    groups: wheel,libvirt,input,docker

- name: configure passwordless sudo and wheel for dnf commands
  copy:
    dest: /etc/sudoers.d/dnf
    owner: root
    group: root
    mode: '0440'
    content: |
      #Allow members of group sudo to execute dnf commands
      Cmnd_Alias DNF = /usr/bin/dnf update, \
                  /usr/bin/dnf upgrade, \
                  /usr/bin/dnf install *, \
                  /usr/bin/dnf remove *, \
                  /usr/bin/dnf search *, \
                  /usr/bin/dnf info * \

      %wheel ALL = NOPASSWD: DNF