---

- name: append user to groups for ubuntu
  user:
    name: "{{ username }}"
    append: yes
    groups: adm,cdrom,sudo,dip,plugdev,input,lpadmin,sambashare,docker
  when: ansible_distribution == "Ubuntu"

- name: append user to groups for debian
  user:
    name: "{{ username }}"
    append: yes
    groups: adm,cdrom,sudo,dip,plugdev,input,docker
  when: ansible_distribution == "Debian"

- name: configure passwordless sudo for apt commands
  copy:
    dest: /etc/sudoers.d/apt
    owner: root
    group: root
    mode: '0440'
    content: |
      #Allow members of group sudo to execute apt commands
      Cmnd_Alias APT = /usr/bin/apt update, \
                 /usr/bin/apt full-upgrade, \
                 /usr/bin/apt full-upgrade -y, \
                 /usr/bin/apt install *, \
                 /usr/bin/apt remove *, \
                 /usr/bin/apt purge *, \
                 /usr/bin/apt autoremove, \
                 /usr/bin/apt autoremove -y \

      %sudo ALL = NOPASSWD: APT
