---

- name: Disable uncommon filesystems
  copy:
    dest: "/etc/modprobe.d/{{ item }}.conf"
    owner: root
    group: root
    mode: '0644'
    content: "install {{ item }} /bin/true"
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - udf
  register: uncommon_filesystem_configs

- name: Remove uncommon network protocol kernel modules
  command: "rmmod {{ item }}"
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - udf
  when: uncommon_filesystem_configs.changed
  ignore_errors: yes