---

- name: Configure Security Limits Hard Core
  copy:
    dest: /etc/security/limits.d/cis_hard_core.conf
    owner: root
    group: root
    mode: '0644'
    content: '* hard core 0'

- name: Configure sysctl SUID dumpable
  copy:
    dest: /etc/sysctl.d/20-cis_suid_dumpable.conf
    owner: root
    group: root
    mode: '0644'
    content: 'fs.suid_dumpable = 0'
  register: cis_sysctl_suid_dumpable

- name: Apply sysctl SUID dumpable
  command: sysctl -p /etc/sysctl.d/20-cis_suid_dumpable.conf
  when: cis_sysctl_suid_dumpable.changed

- name: Configure sysctl Address Space Layout Randomisation
  copy:
    dest: /etc/sysctl.d/20-cis_aslr.conf
    owner: root
    group: root
    mode: '0644'
    content: 'kernel.randomize_va_space = 2'
  register: cis_sysctl_aslr

- name: Apply sysctl Address Space Layout Randomisation
  command: sysctl -p /etc/sysctl.d/20-cis_aslr.conf
  when: cis_sysctl_aslr.changed
