---

- name: import the visual studio code gpg key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: configure the visual studio code yum repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: install visual studio code
  dnf:
    name: code
    state: latest