---

- name: Install auditd package
  ansible.builtin.apt:
    name: auditd
    state: present

- name: Configure auditd
  ansible.builtin.copy:
    src: debian_auditd-rules.d
    dest: /etc/audit/rules.d
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0750'
  notify:
    - Restart auditd service

- name: Enable auditd service
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: yes
  ignore_errors: yes

- name: Configure auditd logrotation
  ansible.builtin.copy:
    dest: /etc/logrotate.d/auditd
    src: debian_auditd-logrotation
    owner: root
    group: root
    mode: '0644'
