---

- name: Configure auditd
  ansible.builtin.copy:
    src: fedora_auditd-rules.d
    dest: /etc/audit/rules.d
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0750'
  notify:
    - Restart auditd service

- name: Enable auditd service
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: yes
