---

- name: configure auditd
  copy:
    src: fedora_auditd-rules.d
    dest: /etc/audit/rules.d
    owner: root
    group: root
    mode: '0640'
    directory_mode: '0750'
  notify:
    - restart auditd service

- name: enable auditd service
  systemd:
    name: auditd
    state: started
    enabled: yes
