---

- ansible.builtin.include: tmp_fedora.yml
- ansible.builtin.include: sysctl.yml
- ansible.builtin.include: filesystems.yml
- ansible.builtin.include: network.yml
- ansible.builtin.include: auditd_fedora.yml

- name: Install apparmor and aa-notify dependencies
  community.general.pacman:
    name:
      - apparmor
      - python-notify2
    state: present

- name: Allow users in audit group to receive auditd notifications
  replace:
    path: /etc/audit/auditd.conf
    regexp: '^log_group \= root'
    replace: 'log_group = audit'

- name: Enable caching of apparmor profiles
  replace:
    path: /etc/apparmor/parser.conf
    regexp: '^#write-cache'
    replace: 'write-cache'

- name: Ensure user config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - "/home/{{ username }}/.config"
    - "/home/{{ username }}/.config/autostart"

- name: Configure desktop launcher for aa-notify notifcations
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/autostart/apparmor-notify.desktop"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    content: |
        [Desktop Entry]
        Type=Application
        Name=AppArmor Notify
        Comment=Receive on screen notifications of AppArmor denials
        TryExec=aa-notify
        Exec=aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log
        StartupNotify=false
        NoDisplay=true

- name: Start and enabled apparmor service
  systemd:
    name: apparmor
    state: started
    enabled: yes
