---

- ansible.builtin.include: tmp_debian.yml
- ansible.builtin.include: sysctl.yml
- ansible.builtin.include: filesystems.yml
- ansible.builtin.include: network.yml
- ansible.builtin.include: auditd_debian.yml
