---

- name: Install hardening for Debian based systems
  ansible.builtin.include_tasks: hardening_debian.yml
  when: ansible_os_family == "Debian"

- name: Install hardening for RedHat based systems
  ansible.builtin.include_tasks: hardening_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install hardening for Arch Linux based systems
  ansible.builtin.include_tasks: hardening_archlinux.yml
  when: ansible_os_family == "Archlinux"
