---

- name: install hardening for Debian based systems
  include_tasks: hardening_debian.yml
  when: ansible_os_family == "Debian"

- name: install hardening for RedHat based systems
  include_tasks: hardening_fedora.yml
  when: ansible_os_family == "RedHat"
