---

- name: Ensure security limits.d directory exists
  file:
    path: /etc/security/limits.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Security Limits Hard Core
  copy:
    dest: /etc/security/limits.d/cis_hard_core.conf
    owner: root
    group: root
    mode: '0644'
    content: '* hard core 0'

- name: Configure sysctl SUID dumpable
  copy:
    dest: /etc/sysctl.d/20-cis_suid_dumpable.conf
    owner: root
    group: root
    mode: '0644'
    content: 'fs.suid_dumpable = 0'
  notify:
    - Apply sysctl SUID dumpable

- name: Configure sysctl Address Space Layout Randomisation
  copy:
    dest: /etc/sysctl.d/20-cis_aslr.conf
    owner: root
    group: root
    mode: '0644'
    content: 'kernel.randomize_va_space = 2'
  notify:
    - Apply sysctl Address Space Layout Randomisation
