---

- name: set systemd tmp.mount file
  copy:
    src: fedora_tmp.mount
    dest: /etc/systemd/system/tmp.mount
    owner: root
    group: root
    mode: '0644'

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: enable tmp.mount to be started on next boot
  systemd:
    name: tmp.mount
    enabled: yes
    masked: no
  notify:
  - manually remount /tmp with noexec permissions
