---

- name: Set systemd tmp.mount file
  ansible.builtin.copy:
    src: debian_tmp.mount
    dest: /etc/systemd/system/tmp.mount
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable tmp.mount to be started on next boot
  ansible.builtin.systemd:
    name: tmp.mount
    enabled: yes
    masked: no
  notify:
    - Manually remount /tmp with noexec permissions

- name: Configure apt to remount tmp with exec permissions
  ansible.builtin.copy:
    src: apt_00exectmp
    dest: /etc/apt/apt.conf.d/apt_00exectmp
    owner: root
    group: root
    mode: '0644'

- name: Ensure all handlers (up until now) are run
  meta: flush_handlers