---

- name: Restart chrony service debian
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Restart chrony service fedora
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
