---

- name: Configure unrestricted boot
  replace:
    path: /etc/grub.d/10_linux
    regexp: "(menuentry\\s.* \\| grub_quote\\)')((?!--unrestricted).)*( \\${CLASS}\\s.+)"
    replace: '\1 --unrestricted\3'
  register: grub_unrestricted_config

- name: Configure grub edit password
  blockinfile:
    path: /etc/grub.d/00_header
    insertafter: EOF
    block: |
      cat << EOF
      set superusers="{{ username }}"
      password_pbkdf2 {{ username }} {{ grub_PBKDF2 }}
      EOF
  register: grub_header_config

- name: Update grub
  command: grub2-mkconfig -o "$(readlink -e /etc/grub2.conf)"
  when: grub_unrestricted_config.changed or grub_header_config.changed


