---

- name: Update grub debian
  ansible.builtin.command:
    cmd: update-grub

- name: Update grub fedora
  ansible.builtin.shell:
    cmd: grub2-mkconfig -o "$(readlink -e {{ grub_path }})"
    chdir: '/'

- name: Update grub archlinux
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
