---

- name: update grub debian
  command: update-grub

- name: update grub fedora
  command: grub2-mkconfig -o "$(readlink -e /etc/grub2.conf)"

- name: update grub archlinux
  command: grub-mkconfig -o /boot/grub/grub.cfg
