---

- name: Ensure VSCodium configuration directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - "/home/{{ username }}/.config/VSCodium"
    - "/home/{{ username }}/.config/VSCodium/User"

- name: Configure VSCodium to use the VSCode repositories for extensions
  ansible.builtin.copy:
    src: product.json
    dest: "/home/{{ username }}/.config/Code/product.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Configure user settings for VSCodium
  ansible.builtin.template:
    src: settings.json.j2
    dest: "/home/{{ username }}/.config/Code/User/settings.json"
    force: no
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0664'
