---

- name: Install vscodium for Debian based systems
  ansible.builtin.include_tasks: vscodium_debian.yml
  when: ansible_os_family == "Debian"

- name: Install vscodium for Fedora based systems
  ansible.builtin.include_tasks: vscodium_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install vscodium for Arch Linux based systems
  ansible.builtin.include_tasks: vscodium_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Install vscodium configuration
  ansible.builtin.include_tasks: vscodium_configuration.yml
  when: ansible_virtualization_role != "guest"
