---

- name: Import the GPG key for VSCodium
  ansible.builtin.rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Configure the package repository for VSCodium
  ansible.builtin.yum_repository:
    name: gitlab.com_paulcarroty_vscodium_repo
    description: gitlab.com_paulcarroty_vscodium_repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Install VSCodium
  ansible.builtin.dnf:
    name: codium
    state: present
    update_cache: yes
