---

- name: check if vmware keymaps is installed
  stat:
    path: /usr/lib/vmware/xkeymap
  register: stat_vmware_keymaps

- name: clone vmware keymaps from aur
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://aur.archlinux.org/vmware-keymaps.git
    dest: /tmp/vmware-keymaps
    version: master
    update: yes
  when: not stat_vmware_keymaps.stat.exists

- name: install vmware keymaps using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/vmware-keymaps
    creates: /usr/lib/vmware/xkeymap
  when: not stat_vmware_keymaps.stat.exists

- name: check if vmware keymaps installation was succesful
  stat:
    path: /usr/lib/vmware/xkeymap
  register: stat_vmwarekeymapsinstalled

- name: remove vmware keymaps cloned repository
  file:
    path: /tmp/vmware-keymaps
    state: absent
  when: stat_vmwarekeymapsinstalled.stat.exists

- name: check if vmware horizon client is installed
  stat:
    path: /usr/bin/vmware-view
  register: stat_horizonclient

- name: clone vmware horizon client from aur
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://aur.archlinux.org/vmware-horizon-client.git
    dest: /tmp/vmware-horizon-client
    version: master
    update: yes
  when: not stat_horizonclient.stat.exists

- name: install vmware horizon client using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/vmware-horizon-client
    creates: /usr/bin/vmware-view
  when: not stat_horizonclient.stat.exists

- name: check if vmware horizon client installation was succesful
  stat:
    path: /usr/bin/vmware-view
  register: stat_vmwarehorizoninstalled

- name: remove vmware horizon client cloned repository
  file:
    path: /tmp/vmware-horizon-client
    state: absent
  when: stat_vmwarehorizoninstalled.stat.exists
