---

- name: ensure /tmp is mounted with exec permissions
  mount:
    path: /tmp
    opts: exec
    state: remounted

- name: download the vmware horizon client installer
  get_url:
    url: https://download3.vmware.com/software/view/viewclients/CART21FQ2/VMware-Horizon-Client-2006-8.0.0-16522670.x64.bundle
    dest: /tmp/VMware-Horizon-Client-2006-8.0.0-16522670.x64.bundle
    mode: '0755'

- name: install vmware horizon client
  command: >-
    /usr/bin/env TERM=dumb VMWARE_EULAS_AGREED=yes
    /tmp/VMware-Horizon-Client-2006-8.0.0-16522670.x64.bundle --console
    --set-setting vmware-horizon-usb usbEnable no
    --set-setting vmware-horizon-smartcard smartcardEnable no
    --set-setting vmware-horizon-rtav rtavEnable no
    --set-setting vmware-horizon-tsdr tsdrEnable no
    --set-setting vmware-horizon-scannerclient scannerEnable no
    --set-setting vmware-horizon-serialportclient serialportEnable no
    --set-setting vmware-horizon-mmr mmrEnable no
    --set-setting vmware-horizon-media-provider mediaproviderEnable no

- name: ensure /tmp is mounted with original permissions
  mount:
    path: /tmp
    state: remounted
