---

- name: Install vmware horizon client for debian and rhel based systems
  include_tasks: horizon_debian_fedora.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Install vmware horizon client for Arch Linux based systems
  include_tasks: horizon_archlinux.yml
  when: ansible_os_family == "Archlinux"
