---

- name: Install vmware horizon client for debian and rhel based systems
  ansible.builtin.include_tasks: horizon_debian_fedora.yml
  when: (ansible_os_family == "Debian" or ansible_distribution == "Fedora") and ansible_virtualization_role != "guest"

- name: Install vmware horizon client for Arch Linux based systems
  ansible.builtin.include_tasks: horizon_archlinux.yml
  when: ansible_os_family == "Archlinux" and ansible_virtualization_role != "guest"
