---

- name: install vmware horizon client for debian and rhel based systems
  include_tasks: horizon_installation.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: install vmware horizon client for Arch Linux based systems
  include_tasks: horizon_archlinux.yml
  when: ansible_os_family == "Archlinux"
