---

- name: add the flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: install flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - com.discordapp.Discord
    - com.microsoft.Teams
    - com.spotify.Client
    - org.gnome.Geary
    - org.telegram.desktop
