---

- name: Add the flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install gnome specific flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - org.gnome.Geary
    - com.transmissionbt.Transmission
  when: desktop_environment == "gnome"
