---

- name: add the flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: install generic flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - com.discordapp.Discord
    - com.microsoft.Teams
    - com.spotify.Client
    - org.telegram.desktop
    - com.bitwarden.desktop

- name: install gnome specific flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - org.gnome.Geary
    - com.transmissionbt.Transmission
  when: desktop_environment == "gnome"

- name: install kde specific flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - com.georgefb.haruna
  when: desktop_environment == "kde"
