---

- name: Add the flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - com.spotify.Client
    - org.telegram
    - com.bitwarden
    - com.discordapp.Discord
    - org.signal.Signal

- name: Install gnome specific flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - org.gnome.Geary
    - com.transmissionbt.Transmission
  when: desktop_environment == "gnome"

- name: Install KDE specific flatpaks from flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
    method: system
  loop:
    - org.kde.neochat
  when: desktop_environment == "kde"
