---

- name: install flatpak for Debian based systems
  include_tasks: flatpak_debian.yml
  when: ansible_os_family == "Debian"

- name: install flatpak for RedHat based systems
  include_tasks: flatpak_fedora.yml
  when: ansible_os_family == "RedHat"

- name: install flatpak packages
  include_tasks: flatpak_packages.yml