---

- name: Install flatpak for Debian based systems
  ansible.builtin.include_tasks: flatpak_debian.yml
  when: ansible_os_family == "Debian"

- name: Install flatpak for RedHat based systems
  ansible.builtin.include_tasks: flatpak_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install flatpak for Arch Linux based systems
  ansible.builtin.include_tasks: flatpak_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Install flatpak packages
  ansible.builtin.include_tasks: flatpak_packages.yml
  when: ansible_virtualization_role != "guest"
