---

- name: Install zsh for Debian based systems
  ansible.builtin.include_tasks: zsh_debian.yml
  when: ansible_os_family == "Debian"

- name: Install zsh for RedHat based systems
  ansible.builtin.include_tasks: zsh_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install zsh for Arch Linux based systems
  ansible.builtin.include_tasks: zsh_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Configure zsh
  ansible.builtin.include_tasks: zsh_configure.yml
