---

- name: Configure zsh for user
  ansible.builtin.template:
    dest: "/home/{{ username }}/.zshrc"
    src: zshrc.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Configure zsh for root
  ansible.builtin.template:
    dest: "/root/.zshrc"
    src: zshrc.j2
    owner: root
    group: root
    mode: '0644'
