---

- name: ensure /usr/local/share exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /usr/local
    - /usr/local/share

- name: create the antigen directory
  file:
    path: /usr/local/share/antigen
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: clone the custom zsh themes directory
  become: false
  git:
    repo: https://github.com/jbouter/zsh-themes.git
    dest: /usr/local/share/antigen/zsh-themes
    version: main
    update: yes

- name: download and install antigen
  become: false
  get_url:
    url: https://git.io/antigen
    dest: /usr/local/share/antigen/antigen.zsh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: configure zsh for user
  template:
    dest: "/home/{{ username }}/.zshrc"
    src: zshrc.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

#- name: set zsh as default shell for user
#  user:
#    name: "{{ username }}"
#    shell: /usr/bin/zsh
