---

- name: Configure zsh for user
  ansible.builtin.template:
    dest: "/home/{{ username }}/.zshrc"
    src: zshrc.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

 - name: set zsh as default shell for user
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
