---

- name: Ensure /usr/local/share exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /usr/local
    - /usr/local/share

- name: Create the antigen directory
  ansible.builtin.file:
    path: /usr/local/share/antigen
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Download and install antigen
  become: false
  get_url:
    url: https://git.io/antigen
    dest: /usr/local/share/antigen/antigen.zsh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Configure zsh for user
  ansible.builtin.template:
    dest: "/home/{{ username }}/.zshrc"
    src: zshrc.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

 - name: set zsh as default shell for user
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
