---

- name: Create touchegg configuration directory for user
  ansible.builtin.file:
    name: "/home/{{ username }}/.config/touchegg"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Configure touchegg for user
  ansible.builtin.copy:
    src: touchegg.conf
    dest: "/home/{{ username }}/.config/touchegg/touchegg.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Start and enable touchegg service
  systemd:
    daemon_reload: yes
    name: touchegg
    enabled: yes
    state: started
  ignore_errors: yes

- name: Create libinput directory
  ansible.builtin.file:
    name: /etc/libinput
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Place libinput quirks
  ansible.builtin.copy:
    src: local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
    owner: root
    group: root
    mode: '0644'

- name: Create xorg configuration directory
  ansible.builtin.file:
    name: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure xorg libinput stuff
  ansible.builtin.copy:
    src: 10-libinput.conf
    dest: /etc/X11/xorg.conf.d/10-libinput.conf
    owner: root
    group: root
    mode: '0644'
