---

- name: create touchegg configuration directory for user
  file:
    name: "/home/{{ username }}/.config/touchegg"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: configure touchegg for user
  copy:
    src: touchegg.conf
    dest: "/home/{{ username }}/.config/touchegg/touchegg.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: start and enable touchegg service
  systemd:
    daemon_reload: yes
    name: touchegg
    enabled: yes
    state: started
  ignore_errors: yes

- name: create libinput directory
  file:
    name: /etc/libinput
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: place libinput quirks
  copy:
    src: local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
    owner: root
    group: root
    mode: '0644'

- name: create xorg configuration directory
  file:
    name: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: configure xorg libinput stuff
  copy:
    src: 10-libinput.conf
    dest: /etc/X11/xorg.conf.d/10-libinput.conf
    owner: root
    group: root
    mode: '0644'
