---

- name: Add touchegg repository and add its signing key
  ansible.builtin.apt_repository:
    repo: ppa:touchegg/stable

- name: Install libinput package requirements
  ansible.builtin.apt:
    name: touchegg
    state: latest
    update_cache: yes