---

- name: install libinput package requirements
  dnf:
    name:
      - xdotool
      - wmctrl
      - ruby
      - libevdev-devel
      - ruby-devel
      - libinput
      - libinput-utils
    state: present