---

- name: Install libinput package requirements
  ansible.builtin.dnf:
    name:
      - xdotool
      - wmctrl
      - libinput
      - libinput-utils
    state: present

- name: Install touchegg
  ansible.builtin.dnf:
    name: 'https://github.com/JoseExposito/touchegg/releases/download/2.0.3/touchegg-2.0.3-1.x86_64.rpm'
    state: present
    disable_gpg_check: yes
