---

- name: Install libinput package requirements
  apt:
    pkg:
    - build-essential
    - libinput-tools
    - ruby
    - wmctrl
    - libevdev-dev
    - ruby-dev

- name: Install ruby gems required by fusuma
  gem:
    name: {{ item }}
    state: present
  with_items:
    - fusuma
    - fusuma-plugin-wmctrl
    - fusuma-plugin-keypress
    - fusuma-plugin-sendkey

- name: Create fusuma configuration directory for {{ username }}
  file:
    name: /home/{{ username }}/.config/fusuma
    state: directory
    owner: {{ username }}
    group: {{ username }}
    mode: '0755'

- name: Configure fusuma for {{ username }}
  get_url:
    url: https://raw.githubusercontent.com/jbouter/libinput-magic-mouse/main/fusuma-config.yml
    dest: /home/{{ username }}/.config/fusuma/config.yml
    owner: {{ username }}
    group: {{ username }}
    mode: '0644'

- name: Create fusuma service
  get_url:
    url: https://raw.githubusercontent.com/jbouter/libinput-magic-mouse/main/fusuma.service
    dest: /etc/systemd/system/fusuma.service
    owner: root
    group: root
    mode: '0755'

- name: Replace 'jeffrey' with {{ username }} in service file
  replace:
    path: /etc/systemd/system/fusuma.service
    regexp: 'jeffrey'
    replace: {{ username }}

- name: Start and enable fusuma service
  systemd:
    daemon_reload: yes
    name: fusuma
    enabled: yes
    state: started
  ignore_errors: yes

- name: Create libinput directory
  file:
    name: /etc/libinput
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Place libinput quirks
  get_url:
    url: https://raw.githubusercontent.com/jbouter/libinput-magic-mouse/master/local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
    owner: root
    group: root
    mode: '0644'

- name: Create xorg configuration directory
  file:
    name: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure xorg libinput stuff
  get_url:
    url: https://raw.githubusercontent.com/jbouter/libinput-magic-mouse/main/10-libinput.conf
    dest: /etc/X11/xorg.conf.d/10-libinput.conf
    owner: root
    group: root
    mode: '0644'
