---

- name: install ruby gems required by fusuma
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  loop:
    - fusuma
    - fusuma-plugin-wmctrl
    - fusuma-plugin-keypress
    - fusuma-plugin-sendkey

- name: create fusuma configuration directory for user
  file:
    name: "/home/{{ username }}/.config/fusuma"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: configure fusuma for user
  copy:
    src: fusuma-config.yml
    dest: "/home/{{ username }}/.config/fusuma/config.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: create fusuma service
  template:
    src: "fusuma.service.j2"
    dest: /etc/systemd/system/fusuma.service
    owner: root
    group: root
    mode: '0644'

- name: start and enable fusuma service
  systemd:
    daemon_reload: yes
    name: fusuma
    enabled: yes
    state: started
  ignore_errors: yes

- name: create libinput directory
  file:
    name: /etc/libinput
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: place libinput quirks
  copy:
    src: local-overrides.quirks
    dest: /etc/libinput/local-overrides.quirks
    owner: root
    group: root
    mode: '0644'

- name: create xorg configuration directory
  file:
    name: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: configure xorg libinput stuff
  copy:
    src: 10-libinput.conf
    dest: /etc/X11/xorg.conf.d/10-libinput.conf
    owner: root
    group: root
    mode: '0644'
