---

- name: Install libinput package requirements
  ansible.builtin.dnf:
    name:
      - xdotool
      - wmctrl
      - libinput
      - libinput-utils
    state: present

- name: Configure the touchegg copr repository
  community.general.copr:
    name: jose_exposito/touchegg

- name: Install touchegg
  ansible.builtin.dnf:
    name: touchegg
    state: present
