---

- name: Install libinput package requirements
  ansible.builtin.apt:
    pkg:
      - build-essential
      - libinput-tools
      - ruby
      - wmctrl

- name: Install touchegg
  ansible.builtin.apt:
    deb: 'https://github.com/JoseExposito/touchegg/releases/download/2.0.7/touchegg_2.0.7_amd64.deb'
