---

- name: install libinput package requirements
  apt:
    pkg:
    - build-essential
    - libinput-tools
    - ruby
    - wmctrl

- name: install touchegg
  apt:
    deb: 'https://github.com/JoseExposito/touchegg/releases/download/2.0.2/touchegg_2.0.2_amd64.deb'
