---

- name: Install iptables packages
  ansible.builtin.apt:
    state: present
    pkg:
      - iptables
      - iptables-persistent
      - netfilter-persistent

- name: Start and enable netfilter-persistent
  ansible.builtin.systemd:
    name: netfilter-persistent
    state: started
    enabled: yes
