---

- name: Install iptables packages
  ansible.builtin.dnf:
    state: present
    name:
      - iptables
      - iptables-services
      - iptables-utils

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Configure automatic iptables saving on stop
  replace:
    path: /etc/sysconfig/iptables-config
    regexp: "^IPTABLES_SAVE_ON_STOP=\"yes\""
    replace: "IPTABLES_SAVE_ON_STOP=\"no\""

- name: Configure automatic iptables saving on restart
  replace:
    path: /etc/sysconfig/iptables-config
    regexp: "^IPTABLES_SAVE_ON_RESTART=\"yes\""
    replace: "IPTABLES_SAVE_ON_RESTART=\"no\""

- name: Start and enable iptables
  ansible.builtin.systemd:
    name: iptables
    state: started
    enabled: yes

- name: Start and enable ip6tables
  ansible.builtin.systemd:
    name: ip6tables
    state: started
    enabled: yes
