---

- name: install iptables packages
  dnf:
    state: present
    name:
      - iptables
      - iptables-services
      - iptables-utils

- name: start and enable iptables
  systemd:
    name: iptables
    state: started
    enabled: yes

- name: start and enable ip6tables
  systemd:
    name: ip6tables
    state: started
    enabled: yes
