---

#
# Set all the iptables defaults
#
#

- name: INPUT - allow all loopback traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify: "run firewall handler"

- name: INPUT - allow all localhost traffic to itself
  iptables:
    chain: INPUT
    source: "127.0.0.1/32"
    destination: "127.0.0.1/32"
    jump: ACCEPT
  notify: "run firewall handler"

- name: INPUT - drop local range
  iptables:
    chain: INPUT
    source: "127.0.0.0/8"
    jump: DROP
  notify: "run firewall handler"

- name: INPUT - allow established and related for TCP and UDP
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    protocol: "{{ item }}"
  loop:
    - tcp
    - udp
  notify: "run firewall handler"

- name: INPUT - allow new, established and related for ICMP
  iptables:
    chain: INPUT
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
    protocol: icmp
  notify: "run firewall handler"

- name: OUTPUT - allow all loopback traffic
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
  notify: "run firewall handler"

- name: OUTPUT - allow new and established
  iptables:
    chain: OUTPUT
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  notify: "run firewall handler"

#
# Allow traffic to KDE Connect
#
#

- name: INPUT - allow traffic to KDE/GS connect TCP/UDP
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: "{{ item }}"
    destination_port: "1716"
    ctstate: NEW
  loop:
    - tcp
    - udp
  notify: "run firewall handler"

#
# Set the default policies of our chains to DROP
#
#

- name: INPUT - default policy DROP
  iptables:
    chain: INPUT
    policy: DROP
  notify: "run firewall handler"

- name: OUTPUT - default policy DROP
  iptables:
    chain: OUTPUT
    policy: DROP
  notify: "run firewall handler"

- name: FORWARD - default policy DROP
  iptables:
    chain: FORWARD
    policy: DROP
  notify: "run firewall handler"


#
# Leave this bit for last; logging dropped packets and ensure
# netfilter-persistent has been started
#
#

- name: INPUT - log prefix with limit
  iptables:
    chain: INPUT
    jump: LOG
    action: append
    limit: "5/min"
    log_prefix: "iptables: ACTION=DROP INPUT: "
  notify: "run firewall handler"

- name: OUTPUT - log prefix with limit
  iptables:
    chain: OUTPUT
    jump: LOG
    action: append
    limit: "5/min"
    log_prefix: "iptables: ACTION=DROP OUTPUT: "
  notify: "run firewall handler"

- name: FORWARD - log prefix with limit
  iptables:
    chain: FORWARD
    jump: LOG
    action: append
    limit: "5/min"
    log_prefix: "iptables: ACTION=DROP FORWARD: "
  notify: "run firewall handler"
