---

- name: Install iptables packages
  community.general.pacman:
    state: present
    name:
      - iptables

- name: Start and enable iptables
  ansible.builtin.systemd:
    name: iptables
    state: started
    enabled: yes

- name: Start and enable ip6tables
  ansible.builtin.systemd:
    name: ip6tables
    state: started
    enabled: yes
