---

- name: Install firewall packages for Debian based systems
  ansible.builtin.include_tasks: firewall_debian.yml
  when: ansible_os_family == "Debian"

- name: Install firewall packages for Fedora based systems
  ansible.builtin.include_tasks: firewall_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install firewall packages for Arch Linux based systems
  ansible.builtin.include_tasks: firewall_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Configure firewall
  ansible.builtin.include_tasks: firewall_global.yml
