---

- name: Run the reflector service
  ansible.builtin.systemd:
    name: reflector
    state: started
    daemon_reload: yes

- name: Initialise informant
  ansible.builtin.command:
    cmd: informant read --all

- name: Stop pcskr kernel module
  community.general.modprobe:
    name: pcspkr
    state: absent
