---

- name: check if root's git config exists
  stat:
    path: /root/.gitconfig
  register: stat_gitconfig

- name: basic git configuration for root user
  copy:
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0640'
    content: |
      [user]
        name = root
        email = root@localhost
      [push]
        default = simple
  when: not stat_gitconfig.stat.exists

- name: install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: install etckeeper"
  apt:
    name: etckeeper
    state: present

- name: configure etckeeper
  copy:
    src: etckeeper_ubuntu.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
