---

- name: install git and etckeeper
  pacman:
    name:
      - git
      - etckeeper
    state: present

- name: configure etckeeper
  copy:
    src: etckeeper_archlinux.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
