---

- name: Install git and etckeeper
  dnf:
    name:
      - git
      - etckeeper
    state: present

- name: Configure etckeeper
  copy:
    src: etckeeper_fedora.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
