---

- name: Install git and etckeeper
  apt:
    pkg:
      - git
      - etckeeper
    state: present
    update_cache: yes

- name: Configure etckeeper
  copy:
    src: etckeeper_ubuntu.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
