---

- name: Check if root's git config exists
  ansible.builtin.stat:
    path: /root/.gitconfig
  register: stat_gitconfig

- name: Basic git configuration for root user
  ansible.builtin.copy:
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0640'
    content: |
      [user]
        name = root
        email = root@localhost
      [push]
        default = simple
      [init]
        defaultBranch = main
  when: not stat_gitconfig.stat.exists

- name: Install etckeeper for Debian based systems
  ansible.builtin.include_tasks: etckeeper_debian.yml
  when: ansible_os_family == "Debian"

- name: Install etckeeper for RedHat based systems
  ansible.builtin.include_tasks: etckeeper_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install etckeeper for Arch Linux based systems
  ansible.builtin.include_tasks: etckeeper_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Initialise etckeeper
  ansible.builtin.command:
    cmd: etckeeper init
  args:
    creates: /etc/.git/config
