---

- name: install GNOME packages
  apt:
    pkg:
      - gnome-session
      - gnome-shell-common
      - gnome-tweaks

- name: configure GDM3 to have default look
  alternatives:
    name: gdm3-theme.gresource
    path: /usr/share/gnome-shell/gnome-shell-theme.gresource
  when: ansible_distribution == "Ubuntu"
