---

- name: configure gnome cursor theme
  dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    state: present
    value: "'Adwaita'"

- name: configure gnome document font name
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    state: present
    value: "'Sans 10'"

- name: configure gnome font name
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    state: present
    value: "'Cantarell 10'"

- name: configure gnome gtk theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    state: present
    value: "'Adwaita'"

- name: configure gnome monospace font
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    state: present
    value: "'Hack 10'"

- name: configure gnome battery percentage in titlebar
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    state: present
    value: "true"

- name: configure gnome desktop background
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    state: present
    value: "'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'"

- name: configure gnome natural scrolling
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    state: present
    value: "true"

- name: disable default gnome alt-tab behavior
  dconf:
    key: "/org/gnome/desktop/wm.keybindings/switch-applications"
    state: present
    value: "[]"

- name: disable default gnome alt-tab backward behavior
  dconf:
    key: "/org/gnome/desktop/wm.keybindings/switch-applications-backward"
    state: present
    value: "[]"

- name: configure windows/kde like alt-tab behavior
  dconf:
    key: "/org/gnome/desktop/wm.keybindings/switch-windows"
    state: present
    value: "['<Alt>Tab', '<Super>Tab']"

- name: configure windows/kde like alt-tab backward behavior
  dconf:
    key: "/org/gnome/desktop/wm.keybindings/switch-windows-backward"
    state: present
    value: "['<Alt><Shift>Tab', '<Super><Shift>Tab']"
