---

- name: configure cursor theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'Adwaita'"

- name: configure document font name
  community.general.dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Sans 10'"

- name: configure font name
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Cantarell 10'"

- name: configure font anti-aliasing
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing"
    value: "'rgba'"

- name: configure font hinting
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/hinting"
    value: "'slight'"

- name: configure gtk theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita'"

- name: configure monospace font
  community.general.dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'Hack 10'"

- name: configure battery percentage in titlebar
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: configure desktop background
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'"

- name: configure natural scrolling
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: enable night light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"

- name: disable default gnome alt-tab behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item }}"
    value: "@as []"
  loop:
    - switch-applications
    - switch-applications-backward

- name: configure windows/kde like alt-tab behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab', '<Super>Tab']"

- name: configure windows/kde like alt-tab backward behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Alt><Shift>Tab', '<Super><Shift>Tab']"

- name: configure favourite apps
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Evolution.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'org.telegram.desktop.desktop', 'com.discordapp.Discord.desktop', 'virt-manager.desktop', 'visual-studio-code.desktop']"
