---

- name: Configure document font name
  community.general.dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Open Sans 10'"

- name: Configure font name (not Ubuntu)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Cantarell 10'"
  when: ansible_distribution != "Ubuntu"

- name: Configure monospace font
  community.general.dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'{{ monospace_font }} 10'"

- name: Configure font name (Ubuntu)
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Ubuntu 10'"
  when: ansible_distribution == "Ubuntu"

- name: Configure font anti-aliasing
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing"
    value: "'rgba'"

- name: Configure font hinting
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/hinting"
    value: "'slight'"

- name: Configure battery percentage in titlebar
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Configure tap to click touchpad
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: Configure two finger scrolling
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"

- name: Configure natural scrolling
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "true"

- name: Enable night light
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"

- name: Disable default gnome alt-tab behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/{{ item }}"
    value: "@as []"
  loop:
    - switch-applications
    - switch-applications-backward

- name: Configure middle-click minimise for windows
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar"
    value: "'minimize'"

- name: Configure windows/kde like alt-tab behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab', '<Super>Tab']"

- name: Configure windows/kde like alt-tab backward behavior
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Alt><Shift>Tab', '<Super><Shift>Tab']"

- name: Configure favourite apps (for Ubuntu)
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Evolution.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'com.bitwarden.desktop.desktop', 'com.spotify.Client.desktop', 'telegram-desktop_telegram-desktop.desktop', 'com.discordapp.Discord.desktop', 'code.desktop', 'vmware-view.desktop']"
  when: ansible_distribution == "Ubuntu"

- name: Configure favourite apps (non) Ubuntu)
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Evolution.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'com.bitwarden.desktop.desktop', 'com.spotify.Client.desktop', 'org.telegram.desktop', 'com.discordapp.Discord.desktop', 'code.desktop', 'vmware-view.desktop']"
  when: ansible_distribution != "Ubuntu"

- name: Configure screenshot keyboard shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: "['<Shift><Alt>numbersign']"

- name: Configure screenshot current window keyboard shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/window-screenshot"
    value: "['<Shift><Alt>at']"

- name: Configure screenshot area keyboard shortcut
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot"
    value: "['<Shift><Alt>dollar']"

- name: Configure gnome-terminal keyboard shortcut binding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Primary><Alt>t'"

- name: Configure gnome-terminal keyboard shortcut command
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'gnome-terminal'"

- name: Configure gnome-terminal keyboard shortcut name
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'gnome-terminal'"
