---

- name: Install GNOME packages
  ansible.builtin.apt:
    pkg:
      - gnome-session
      - gnome-shell-common
      - gnome-tweaks
      - gnome-backgrounds

- name: Install suru on Debian
  ansible.builtin.apt:
    name: suru-icon-theme
  when: ansible_distribution == "Debian"
