---

- name: install gnome for Debian based systems
  include_tasks: gnome_debian.yml
  when: ansible_os_family == "Debian"

- name: install gnome for RedHat based systems
  include_tasks: gnome_fedora.yml
  when: ansible_os_family == "RedHat"
