---

- name: Configure the Google Chrome yum repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: latest