# Update PATH
export PATH=$PATH:$HOME/.local/bin:/usr/local/sbin:/usr/sbin:/sbin

# Custom aliases
alias ls='ls -F --color=auto'
alias l='ls -F'
alias ll='ls -l'
alias la='ls -las'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias duh='du -hsx * 2>/dev/null | sort -hr | head -n 6'
alias ip='ip -c'

# Virsh
alias virsh='virsh -c qemu:///system'
alias virt-viewer='virt-viewer -c qemu:///system'
alias virt-install='virt-install --connect qemu:///system'

# custom function to start a new SSH session in a new tmux window
function t () {
  tmux new-window -n "$1" "ssh $1"
}

# Set TERM if using kitty
if [ "$TERM" == "xterm-kitty" ]; then
  export TERM="xterm-256color"
fi

# fbd
# fbd - delete git branch (including remote branches)
fbd() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" | fzf --multi ) &&
  git branch -D $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}
