---

- name: check if google chrome is installed
  stat:
    path: /usr/bin/google-chrome-stable
  register: stat_chrome

- name: clone Google Chrome from aur
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://aur.archlinux.org/google-chrome.git
    dest: /tmp/google-chrome
    version: master
    update: yes
  when: not stat_chrome.stat.exists

- name: install Google Chrome using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/google-chrome
    creates: /usr/bin/google-chrome-stable
  when: not stat_chrome.stat.exists

- name: check if google chrome installation was succesful
  stat:
    path: /usr/bin/code
  register: stat_chromeinstalled

- name: remove google chrome cloned repository
  file:
    path: /tmp/google-chrome
    state: absent
  when: stat_chromeinstalled.stat.exists
