---

- name: import the google chrome gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.google.com/linux/linux_signing_key.pub

- name: configure the Google Chrome yum repository
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

- name: install Google Chrome
  ansible.builtin.dnf:
    name: google-chrome-stable
    state: latest