---

- name: add Google Chrome repository key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: check if Google Chrome apt repository exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: gchrome_stat_result

- name: configure Google Chrome repository
  ansible.builtin.apt_repository:
    filename: google-chrome
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  when:
    - not gchrome_stat_result.stat.exists

- name: install Google Chrome package
  ansible.builtin.apt:
    update_cache: yes
    state: present
    name: google-chrome-stable