---

- name: install Google Chrome for Debian based systems
  ansible.builtin.include_tasks: chrome_debian.yml
  when: ansible_os_family == "Debian"

- name: install Google Chrome for Fedora based systems
  ansible.builtin.include_tasks: chrome_fedora.yml
  when: ansible_distribution == "Fedora"

- name: install Google Chrome for Arch Linux based systems
  ansible.builtin.include_tasks: chrome_archlinux.yml
  when: ansible_os_family == "Archlinux"
