---

- name: install Google Chrome for Debian based systems
  include_tasks: chrome_debian.yml
  when: ansible_os_family == "Debian"

- name: install Google Chrome for RedHat based systems
  include_tasks: chrome_fedora.yml
  when: ansible_os_family == "RedHat"

- name: install Google Chrome for Arch Linux based systems
  include_tasks: chrome_archlinux.yml
  when: ansible_os_family == "Archlinux"
