---

- name: Install chrony
  dnf:
    name: chrony
    state: present

- name: Stop and disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no
    masked: yes

- name: Configure timezone to be Europe/Amsterdam
  file:
    src: /usr/share/zoneinfo/Europe/Amsterdam
    dest: /etc/localtime
    state: link

- name: Configure chronyd service
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Configure chrony
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  register: configure_chrony

- name: Restart chrony service
  systemd:
    name: chronyd
    state: restarted
  when: configure_chrony.changed
