---

- name: Check if starship is installed
  ansible.builtin.stat:
    path: /usr/local/bin/starship
  register: stat_starship

- name: Download the starship installer
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0640'
  when: not stat_starship.stat.exists

- name: Install starship
  ansible.builtin.command:
    cmd: bash /tmp/starship_install.sh -f
    creates: /usr/local/bin/starship
