---

- name: Check if starship is installed
  ansible.builtin.stat:
    path: /usr/bin/starship
  register: stat_starship

- name: Clone starship from aur
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/starship-bin.git
    dest: /tmp/starship
    version: master
    update: yes
  when: not stat_starship.stat.exists

- name: Install starship using makepkg
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: makepkg --noconfirm -si
  args:
    chdir: /tmp/starship
    creates: /usr/bin/starship
  when: not stat_starship.stat.exists

- name: Check if starship installation was succesful
  ansible.builtin.stat:
    path: /usr/bin/starship
  register: stat_starshipinstalled

- name: Remove starship cloned repository
  ansible.builtin.file:
    path: /tmp/starship
    state: absent
  when: stat_starshipinstalled.stat.exists
