---

- name: Create pipewire config directories for user
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - "/home/{{ username }}/.config/pipewire"
    - "/home/{{ username }}/.config/pipewire/media-session.d"

- name: Create alsa-monitor pipewire configuration
  ansible.builtin.copy:
    src: alsa-monitor.conf
    dest: "/home/{{ username }}/.config/pipewire/media-session.d/alsa-monitor.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Ensure pulseaudio services are stopped
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    state: stopped
    enabled: no
    name: pulseaudio
    scope: user
  ignore_errors: yes

- name: Ensure pipewire services are enabled
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
    scope: user
  loop:
    - pipewire
    - pipewire-pulse
  notify:
    - Restart pipewire services

- name: Ensure pipewire-media-session is enabled
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    enabled: yes
    name: pipewire-media-session
    scope: user
  notify:
    - Restart pipewire media session
  when: ansible_distribution != "Fedora"
