swipe:
  3:
    left:
      # History forward
      sendkey: "LEFTALT+RIGHT"
    right:
      # History back
      sendkey: "LEFTALT+LEFT"
  4:
    left:
      # Switch to next workspace
      workspace: 'next'
      keypress:
        # Move window to next workspace
        LEFTSHIFT:
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+RIGHT"
    right:
      # Switch to previous workspace
      workspace: 'prev'
      keypress:
        LEFTSHIFT:
          # Move window to previous workspace
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+LEFT"
    up:
      # Switch to next workspace
      workspace: 'next'
      keypress:
        LEFTSHIFT:
          # Move window to next workspace
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+UP"
    down:
      # Switch to previous workspace
      workspace: "prev"
      keypress:
        LEFTSHIFT:
          # Move window to previous workspace
          sendkey: "LEFTCTRL+LEFTALT+LEFTSHIFT+DOWN"

pinch:
  2:
    in:
      # Lock the screen
      sendkey: "LEFTMETA+L"
    #out:
    #  command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out
  3:
    in:
      # Open overview
      sendkey: "LEFTMETA"
  4:
    in:
      # Open overview
      sendkey: "LEFTMETA"

rotate:
  3:
    clockwise:
      sendkey: "BRIGHTNESSUP"
    counterclockwise:
      sendkey: "BRIGHTNESSDOWN"

plugin:
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
