---
- hosts: localhost
  become: yes
  ask_become_pass: yes
  roles:
    - etckeeper
    - base_packages
    - gnome
    - flatpak
    - grub
    - nextcloud
    - hardening
    - chrony
    - user
    - chrome
    - libinput
    - vscode
    - virtualisation