---

- name: configure unrestricted boot
  replace:
    path: /etc/grub.d/10_linux
    regexp: "(menuentry\\s.* \\| grub_quote\\)')((?!--unrestricted).)*( \\${CLASS}\\s.+)"
    replace: '\1 --unrestricted\3'
  notify:
    - update grub archlinux

- name: configure grub edit password
  blockinfile:
    path: /etc/grub.d/00_header
    insertafter: EOF
    block: |
      cat << EOF
      set superusers="{{ username }}"
      password_pbkdf2 {{ username }} {{ grub_PBKDF2 }}
      EOF
  notify:
  - update grub archlinux
