---

- name: Find the grub EFI file
  ansible.builtin.stat:
    path: /etc/grub2-efi.cfg
  register: stat_grub_efi

- name: Set grub_path fact to efi
  ansible.builtin.set_fact: grub_path="/etc/grub2-efi.cfg"
  when: stat_grub_efi.stat.exists

- name: Set grub_path fact to non-efi
  ansible.builtin.set_fact: grub_path="/etc/grub2.cfg"
  when: not stat_grub_efi.stat.exists

- name: Configure unrestricted boot
  ansible.builtin.replace:
    path: /etc/grub.d/10_linux
    regexp: "(menuentry\\s.* \\| grub_quote\\)')((?!--unrestricted).)*( \\${CLASS}\\s.+)"
    replace: '\1 --unrestricted\3'
  notify:
    - Update grub fedora

- name: Configure grub edit password
  ansible.builtin.blockinfile:
    path: /etc/grub.d/00_header
    insertafter: EOF
    block: |
      cat << EOF
      set superusers="{{ username }}"
      password_pbkdf2 {{ username }} {{ grub_PBKDF2 }}
      EOF
  notify:
    - Update grub fedora

- name: Configure grub timeout to be 0 seconds instead of 5
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT=5$"
    replace: 'GRUB_TIMEOUT=0'
  notify: Update grub fedora
