---

- name: Default grub configuration
  ansible.builtin.copy:
    src: debian_default-grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
    force: no
  notify:
    - Update grub debian

- name: Configure unrestricted boot
  ansible.builtin.replace:
    path: /etc/grub.d/10_linux
    regexp: "(menuentry\\s.* \\| grub_quote\\)')((?!--unrestricted).)*( \\${CLASS}\\s.+)"
    replace: '\1 --unrestricted\3'
  notify:
    - Update grub debian

- name: Configure grub edit password
  ansible.builtin.blockinfile:
    path: /etc/grub.d/00_header
    insertafter: EOF
    block: |
      cat << EOF
      set superusers="{{ username }}"
      password_pbkdf2 {{ username }} {{ grub_PBKDF2 }}
      EOF
  notify:
    - Update grub debian
