---

- name: Install grub for Debian based systems
  ansible.builtin.include_tasks: grub_debian.yml
  when: ansible_os_family == "Debian"

- name: Install grub for Fedora based systems
  ansible.builtin.include_tasks: grub_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install grub for Arch Linux based systems
  ansible.builtin.include_tasks: grub_archlinux.yml
  when: ansible_os_family == "Archlinux"
