---

- name: Install grub for Debian based systems
  ansible.builtin.include_tasks: grub_debian.yml
  when: ansible_os_family == "Debian"

- name: Install grub for RedHat based systems
  ansible.builtin.include_tasks: grub_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install grub for Arch Linux based systems
  ansible.builtin.include_tasks: grub_archlinux.yml
  when: ansible_os_family == "Archlinux"
