---

- name: install all requirements for Debian based systems
  include_tasks: setup_debian.yml
  when: ansible_os_family == "Debian"

- name: install all requirements for RedHat based systems
  include_tasks: setup_fedora.yml
  when: ansible_os_family == "RedHat"
