---

- name: install all requirements for Debian based systems
  include_tasks: packages_debian.yml
  when: ansible_os_family == "Debian"

- name: install all requirements for RedHat based systems
  include_tasks: packages_fedora.yml
  when: ansible_os_family == "RedHat"

- name: install all requirements for Arch Linux based systems
  include_tasks: packages_archlinux.yml
  when: ansible_os_family == "Archlinux"
