---

- name: Install all requirements for Debian based systems
  ansible.builtin.include_tasks: packages_debian.yml
  when: ansible_os_family == "Debian"

- name: Install all requirements for RedHat based systems
  ansible.builtin.include_tasks: packages_fedora.yml
  when: ansible_os_family == "RedHat"

- name: Install all requirements for Arch Linux based systems
  ansible.builtin.include_tasks: packages_archlinux.yml
  when: ansible_os_family == "Archlinux"
