---

- name: update all packages to the latest version
  pacman:
    update_cache: yes
    upgrade: yes

- name: install base packages
  pacman:
    state: present
    name:
      - htop
      - atop
      - iotop
      - borgbackup
      - ffmpeg
      - imagemagick
      - libreoffice-fresh
      - pwgen
      - wireguard-tools
      - tmux
      - vim
      - adb
      - fastboot
      - pass
      - gnupg
      - fzf
      - pass
      - rofi
      - ttf-cascadia-code
      - neofetch
      - fprintd
      - bluez
      - bluez-utils

- name: clone yay from aur
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
    update: yes

- name: install yay using makepkg
  become: yes
  become_user: "{{ username }}"
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay

- name: start and enable fprintd
  systemd:
    name: fprintd
    state: started
    enabled: True

- name: start and enable the bluetooth daemon
  systemd:
    name: bluetooth
    state: started
    enabled: True
