---

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  apt:
    state: present
    pkg:
    - htop
    - atop
    - iotop
    - direnv
    - borgbackup
    - ffmpeg
    - imagemagick
    - libreoffice-base-core
    - libreoffice-writer
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-gtk3
    - pwgen
    - wireguard
    - tmux
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - vim
    - adb
    - fastboot
    - pass
    - gnupg2

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Configure vim to be the default editor systemd wide
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
