---

- name: Configure DNF to be even better
  ansible.builtin.copy:
    src: dnf.conf
    dest: /etc/dnf/dnf.conf
    mode: '0644'
    owner: root
    group: root

- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install RPMFusion Free
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install RPMFusion NonFree
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - htop
      - atop
      - iotop
      - direnv
      - borgbackup
      - ffmpeg
      - ImageMagick
      - libreoffice
      - libreoffice-gtk3
      - pwgen
      - wireguard-tools
      - qemu
      - qemu-kvm
      - libvirt-daemon
      - virt-manager
      - tmux
      - vim
      - adb
      - fastboot
      - gnupg2
      - nextcloud-client
      - nextcloud-client-nautilus
      - fzf
      - python3-psutil
      - pavucontrol
      - openssl
      - resolvconf
      - systemd-oom
      - yamllint
      - meson
      - PackageKit
      - PackageKit-command-not-found
      - tlp

- name: Install Development Tools group package
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present

- name: Install multimedia group package
  ansible.builtin.dnf:
    name: '@Multimedia'
    state: latest

- name: Start & enable systemd-oomd
  ansible.builtin.systemd:
    name: systemd-oomd
    state: started
    enabled: yes

- name: Disable pcspkr kernel module
  ansible.builtin.copy:
    dest: /etc/modprobe.d/pcspkr.conf
    owner: root
    group: root
    mode: '0644'
    content: 'blacklist pcspkr'
  notify: Stop pcskr kernel module
