---

- name: Update all packages to the latest version
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  community.general.pacman:
    state: present
    name:
      - htop
      - atop
      - iotop
      - borgbackup
      - bash-completion
      - ffmpeg
      - imagemagick
      - libreoffice-fresh
      - pwgen
      - wireguard-tools
      - tmux
      - vim
      - adb
      - fastboot
      - android-udev
      - gnupg
      - fzf
      - fprintd
      - bluez
      - bluez-utils
      - python-psutil
      - reflector
      - openbsd-netcat
      - cups
      - pavucontrol
      - resolvconf
      - earlyoom
      - yamllint
      - aspell-en
      - hunspell-en_GB
      - meson

- name: Clone yay from aur
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
    update: yes

- name: Install yay using makepkg
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: makepkg --noconfirm -si
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay

- name: Clone informant from aur
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/informant.git
    dest: /tmp/informant
    version: master
    update: yes

- name: Install informant using makepkg
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: makepkg --noconfirm -si
  args:
    chdir: /tmp/informant
    creates: /usr/bin/informant
  notify: "Initialise informant"

- name: Start and enable fprintd
  ansible.builtin.systemd:
    name: fprintd
    state: started
    enabled: yes

- name: Start and enable the bluetooth daemon
  ansible.builtin.systemd:
    name: bluetooth
    state: started
    enabled: yes

- name: Start and enable the cups daemon
  ansible.builtin.systemd:
    name: cups
    state: started
    enabled: yes

- name: Create config directories
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop:
    - /etc/xdg/reflector
    - /etc/pacman.d/hooks

- name: Create the reflector configuration file
  ansible.builtin.copy:
    dest: /etc/xdg/reflector/reflector.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      --save /etc/pacman.d/mirrorlist
      --country Netherlands
      --protocol https
      --latest 5
  notify: "Run the reflector service"

- name: Create the pacman hook for reflector
  ansible.builtin.copy:
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    owner: root
    group: root
    mode: '0644'
    content: |
      [Trigger]
      Operation = Upgrade
      Type = Package
      Target = pacman-mirrorlist

      [Action]
      Description = Updating pacman-mirrorlist with reflector and removing pacnew...
      When = PostTransaction
      Depends = reflector
      Exec = /bin/sh -c 'systemctl start reflector.service; if [ -f /etc/pacman.d/mirrorlist.pacnew ]; then rm /etc/pacman.d/mirrorlist.pacnew; fi'
  notify: "Run the reflector service"

- name: Start & enable service earlyoom
  ansible.builtin.systemd:
    name: earlyoom
    state: started
    enabled: yes
