---

- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install RPMFusion Free
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install RPMFusion NonFree
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - htop
      - atop
      - iotop
      - direnv
      - borgbackup
      - ffmpeg
      - ImageMagick
      - libreoffice
      - libreoffice-gtk3
      - pwgen
      - wireguard-tools
      - qemu
      - qemu-kvm
      - libvirt-daemon
      - virt-manager
      - tmux
      - vim
      - adb
      - fastboot
      - gnupg2
      - nextcloud-client
      - nextcloud-client-nautilus
      - fzf
      - python3-psutil
      - pavucontrol
      - openssl
      - resolvconf
      - earlyoom
      - yamllint
      - meson
      - PackageKit
      - PackageKit-command-not-found

- name: Install Development Tools group package
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present

- name: Start & enable service earlyoom
  ansible.builtin.systemd:
    name: earlyoom
    state: started
    enabled: yes
