---

- name: Restart pipewire services
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    state: restarted
    name: "{{ item }}"
    scope: user
  loop:
    - pipewire
    - pipewire-pulse
    - pipewire-media-session