---

- name: Restart pipewire services
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    state: restarted
    name: "{{ item }}"
    scope: user
  loop:
    - pipewire
    - pipewire-pulse

- name: Restart pipewire media session
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    state: restarted
    name: pipewire-media-session
    scope: user
