---

- name: Install base packages
  ansible.builtin.apt:
    state: present
    pkg:
      - fonts-cantarell
      - fonts-hack-ttf
      - fonts-open-sans
      - fonts-ubuntu
      - fonts-firacode
      - fonts-cascadia-code

- name: Create JetBrains mono fonts directory
  ansible.builtin.file:
    dest: /usr/local/share/fonts/JetBrainsMono
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Download and extract JetBrains Mono
  ansible.builtin.unarchive:
    src: "https://github.com/JetBrains/JetBrainsMono/releases/\
          download/v2.225/JetBrainsMono-2.225.zip"
    dest: /usr/local/share/fonts/JetBrainsMono
    remote_src: yes

- name: Configure fontconfig for user
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_generic.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
