---

- name: Install font packages
  community.general.pacman:
    state: present
    name:
      - terminus-font
      - cantarell-fonts
      - ttf-hack
      - ttf-liberation
      - ttf-opensans
      - ttf-ubuntu-font-family
      - noto-fonts-emoji

- name: Enable sub-pixel-rgb font hinting
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    owner: root
    group: root
    state: link

- name: Configure fontconfig for user
  ansible.builtin.template:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_arch.conf.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Configure Terminus in vconsole font
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      FONT=ter-p16n
      FONT_MAP=8859-2
