---

- name: Install base packages
  ansible.builtin.apt:
    state: present
    pkg:
      - fonts-cantarell
      - fonts-hack-ttf
      - fonts-open-sans
      - fonts-ubuntu
      - fonts-firacode

- name: Configure fontconfig for user
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_generic.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
