---

- name: install font packages
  pacman:
    state: present
    name:
      - ttf-cascadia-code
      - adobe-source-code-pro-fonts
      - cantarell-fonts

- name: enable sub-pixel-rgb font hinting
  file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    owner: root
    group: root
    state: link

- name: configure fontconfig for user
  copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_arch.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
