---

- name: Install font packages
  community.general.pacman:
    state: present
    name:
      - cantarell-fonts
      - ttf-hack
      - ttf-liberation
      - ttf-opensans
      - ttf-ubuntu-font-family
      - noto-fonts-emoji
      - ttf-fira-code

- name: Enable sub-pixel-rgb font hinting
  ansible.builtin.file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    owner: root
    group: root
    state: link

- name: Configure fontconfig for user
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_arch.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
