---

- name: Install base packages
  ansible.builtin.apt:
    state: present
    pkg:
      - fonts-cascadia-code
      - fonts-cantarell
      - fonts-hack-ttf
      - fonts-open-sans
      - fonts-firacode

- name: Create local fonts directory
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  loop:
    - /usr/local/share/fonts
    - /usr/local/share/fonts/source-code-pro
    - /usr/local/share/fonts/roboto-mono
    - /usr/local/share/fonts/iosevka-term-curly

- name: Download and extract source code pro
  unarchive:
    src: https://fonts.google.com/download?family=Source%20Code%20Pro
    dest: /usr/local/share/fonts/source-code-pro
    remote_src: yes

- name: Download and extract roboto mono
  unarchive:
    src: https://fonts.google.com/download?family=Roboto%20Mono
    dest: /usr/local/share/fonts/roboto-mono
    remote_src: yes

- name: Download and extract Iosevka Term Curly
  unarchive:
    src: "https://github.com/be5invis/Iosevka/releases/\
          download/v4.4.0/ttf-iosevka-term-curly-4.4.0.zip"
    dest: /usr/local/share/fonts/iosevka-term-curly
    remote_src: yes

- name: Configure fontconfig for user
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_generic.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
