---

- name: Install base packages
  ansible.builtin.apt:
    state: present
    pkg:
      - xfonts-terminus
      - fonts-cantarell
      - fonts-hack-ttf
      - fonts-open-sans
      - fonts-ubuntu

- name: Create JetBrains mono fonts directory
  ansible.builtin.file:
    dest: /usr/local/share/fonts/JetBrainsMono
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Download and extract JetBrains Mono
  ansible.builtin.unarchive:
    src: "https://github.com/JetBrains/JetBrainsMono/releases/\
          download/v2.225/JetBrainsMono-2.225.zip"
    dest: /usr/local/share/fonts/JetBrainsMono
    remote_src: yes

- name: Configure fontconfig for user
  ansible.builtin.template:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_generic.conf.j2
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Configure the TTY font to use Terminus
  ansible.builtin.replace:
    path: /etc/default/console-setup
    regexp: "^FONTFACE=\"Fixed\""
    replace: "FONTFACE=\"Terminus\""
  notify: Regenerate initramfs for Debian

- name: Configure Terminus in vconsole font
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      FONT=ter-p16n
      FONT_MAP=8859-2
