---

- name: Install font packages
  ansible.builtin.dnf:
    name:
      - abattis-cantarell-fonts
      - open-sans-fonts
      - fira-code-fonts

- name: Create Hack fonts directory
  ansible.builtin.file:
    dest: /usr/local/share/fonts/hack
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Download and extract hack
  ansible.builtin.unarchive:
    src: "https://github.com/source-foundry/Hack/releases\
          /download/v3.003/Hack-v3.003-ttf.zip"
    dest: /usr/local/share/fonts/hack
    remote_src: yes

- name: Configure fontconfig for user
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.config/fontconfig/fonts.conf"
    src: fonts_generic.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
