---

- name: Create fontconfig directory for user
  ansible.builtin.file:
    dest: "/home/{{ username }}/.config/fontconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
    state: directory

- name: Create local fonts directory
  ansible.builtin.file:
    dest: /usr/local/share/fonts
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Install fonts for Debian based systems
  ansible.builtin.include_tasks: fonts_debian.yml
  when: ansible_os_family == "Debian"

- name: Install fonts for Fedora based systems
  ansible.builtin.include_tasks: fonts_fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install fonts for Arch Linux based systems
  ansible.builtin.include_tasks: fonts_archlinux.yml
  when: ansible_os_family == "Archlinux"
